version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: dennn88/foodgram_front:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - db

  backend:
    image: dennn88/foodgram:v1.0.2
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  db_data:
  result_build:
