# Generated by Django 4.1.3 on 2022-11-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='teg',
            new_name='tag',
        ),
    ]
